### ISSUE TITLE
trivial check in a python script

### ISSUE THREAD

**Issue by SHuang-Broad** [PacificBiosciences/hg002-ccs#2]
When trying to run the script `smallvariants/decompose_multiallelic_sites.py`, I run into the following error (line numbers are slightly off as I've added several lines at the beginning)

```
Traceback (most recent call last):
  File "decompose_multiallelic_sites.py", line 113, in <module>
    sys.exit(main(sys.argv[1:]))
  File "decompose_multiallelic_sites.py", line 108, in main
    for outrow in decompose_multiallelic(row):
  File "decompose_multiallelic_sites.py", line 83, in decompose_multiallelic
    info = decompose_INFO(INFO, position)
  File "decompose_multiallelic_sites.py", line 25, in decompose_INFO
    annotation, values = infofield.split('=')
ValueError: need more than 1 value to unpack
```

Following the Stack trace, I think [this](https://github.com/PacificBiosciences/hg002-ccs/blob/c5ee05f7457df7d98d5ca3e24e8042af481f3f47/smallvariants/decompose_multiallelic_sites.py#L21) line should do a check for `INFO` annotations of `FLAG` type (i.e. they have no associated value hence there won't be a "=").

**Comment by williamrowell** [comment]
Hi @SHuang-Broad,

Thanks for your interest in this repository and the publication.  The point of this repository is to maintain a record of the scripts used in the publication.  It appears that this error is due to new values in the unfiltered VCF resulting from upstream differences in GATK parameters.  This script is definitely brittle, imperfect, and not robust to upstream changes, but since we don't recommend this script as part of our current variant detection workflow, I don't intend to develop this script any further for the moment.  If you find this script to be useful for your research, please feel free to fork the repository and make changes in your branch.

We currently recommend [DeepVariant](https://github.com/google/deepvariant) for small variant detection in HiFi reads, but we're always open to evaluating and recommending alternatives with similar performance.
